@startuml
autonumber
actor "User" as U
participant ":System" as SYS


activate U
U -> SYS : Want to schedule a meeting
activate SYS
SYS --> U : Informs if the meeting was scheduled with success or not
deactivate SYS
deactivate U

@enduml