@startuml
autonumber
'hide footbox
actor "Student" as student

participant ":ShowNextExamsUI" as ui
participant ":ShowNextExamsController" as ctrl
participant ":ShowNextExamsService" as srvc

database ":ExamRepository" as repo

activate student

student -> ui: show()
activate ui

ui -> ui: doShow()



ui -> ctrl : showNextExams(email)
activate ctrl

ctrl -> srvc: create()
activate srvc

ctrl -> srvc: showNextExams(email)

srvc -> repo: create()
activate repo
srvc -> repo: showNextExams(email)
deactivate repo

srvc --> ctrl: return exams list
deactivate srvc

ctrl --> ui: return exams list
deactivate ctrl


ui --> student:
deactivate ui




@enduml