@startuml
autonumber
actor "User" as U
participant ":System" as SYS


activate U
U -> SYS : Want to cancel a meeting
activate SYS
SYS --> U : Informs if the meeting was canceled with success or not
deactivate SYS
deactivate U

@enduml